sonar.projectKey=VidiomTM_subtitle-correction
sonar.organization=vidiomtm
sonar.qualitygate.wait=true

# Source paths
sonar.sources=subtitle_correction
sonar.tests=tests

# Coverage
sonar.python.coverage.reportPaths=coverage.xml
