sonar.projectKey=Jonathangadeaharder_subtitle-correction
sonar.organization=jonathangadeaharder
sonar.host.url=https://sonarcloud.io
sonar.sources=subtitle_correction
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.12
